name: SonarQube Quality check 
on:
  push:
   
jobs:
  build:
    name: Build
    runs-on: [self-hosted, sonarqube]
    env:
      SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      SONAR_KEY: ${{ secrets.SONAR_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        run : |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          ./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.projectKey=$SONAR_KEY -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_LOGIN 